// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFnxe-K0VJ1NZvhypsksQNg37k0kI02Qc',
    appId: '1:525739732141:web:a619902f34c62595436a24',
    messagingSenderId: '525739732141',
    projectId: 'flutter-5c-5',
    authDomain: 'flutter-5c-5.firebaseapp.com',
    storageBucket: 'flutter-5c-5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy3S_IPzIGmzyaAeROjV-zQGRvMCfuMkc',
    appId: '1:525739732141:android:4cfac6e786111754436a24',
    messagingSenderId: '525739732141',
    projectId: 'flutter-5c-5',
    storageBucket: 'flutter-5c-5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjju4wBcIIOutMNaahxbIyfJ4Mp3JiVXQ',
    appId: '1:525739732141:ios:ed2d7c066bf774d5436a24',
    messagingSenderId: '525739732141',
    projectId: 'flutter-5c-5',
    storageBucket: 'flutter-5c-5.firebasestorage.app',
    iosBundleId: 'com.example.applicationFirebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjju4wBcIIOutMNaahxbIyfJ4Mp3JiVXQ',
    appId: '1:525739732141:ios:ed2d7c066bf774d5436a24',
    messagingSenderId: '525739732141',
    projectId: 'flutter-5c-5',
    storageBucket: 'flutter-5c-5.firebasestorage.app',
    iosBundleId: 'com.example.applicationFirebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFnxe-K0VJ1NZvhypsksQNg37k0kI02Qc',
    appId: '1:525739732141:web:e40a62b5d5eb2a30436a24',
    messagingSenderId: '525739732141',
    projectId: 'flutter-5c-5',
    authDomain: 'flutter-5c-5.firebaseapp.com',
    storageBucket: 'flutter-5c-5.firebasestorage.app',
  );
}
